// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates a custom meal plan based on user dietary needs, restrictions,
 * preferred ingredients, and desired calorie intake.
 *
 * - generateCustomMealPlan - A function that generates a custom meal plan.
 * - GenerateCustomMealPlanInput - The input type for the generateCustomMealPlan function.
 * - GenerateCustomMealPlanOutput - The return type for the generateCustomMealPlan function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateCustomMealPlanInputSchema = z.object({
  dietaryRestrictions: z
    .string()
    .describe('Any dietary restrictions the user has (e.g., gluten-free, vegetarian, vegan).'),
  preferredIngredients: z
    .string()
    .describe('Ingredients the user prefers to include in their meal plan.'),
  calorieIntake: z
    .number()
    .describe('The desired daily calorie intake for the meal plan.'),
  numberOfMeals: z.number().describe('The number of meals to include in the meal plan (e.g., 3 for breakfast, lunch, and dinner).'),
});

export type GenerateCustomMealPlanInput = z.infer<
  typeof GenerateCustomMealPlanInputSchema
>;

const GenerateCustomMealPlanOutputSchema = z.object({
  mealPlan: z
    .string()
    .describe(
      'A detailed meal plan that includes recipes, ingredients, and instructions, considering dietary restrictions, preferred ingredients, and desired calorie intake.'
    ),
});

export type GenerateCustomMealPlanOutput = z.infer<
  typeof GenerateCustomMealPlanOutputSchema
>;

export async function generateCustomMealPlan(
  input: GenerateCustomMealPlanInput
): Promise<GenerateCustomMealPlanOutput> {
  return generateCustomMealPlanFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateCustomMealPlanPrompt',
  input: {schema: GenerateCustomMealPlanInputSchema},
  output: {schema: GenerateCustomMealPlanOutputSchema},
  prompt: `You are a personal nutrition coach. Your job is to create personalized meal plans for users based on their dietary restrictions, preferred ingredients, and desired calorie intake.

  Consider the following when generating the meal plan:
  * Dietary Restrictions: {{{dietaryRestrictions}}}
  * Preferred Ingredients: {{{preferredIngredients}}}
  * Desired Calorie Intake: {{{calorieIntake}}} calories
  * Number of Meals: {{{numberOfMeals}}}

  Create a meal plan that is both healthy and enjoyable for the user.
  Format the meal plan to be easy to follow with clear instructions and nutritional information for each meal.
  `,
});

const generateCustomMealPlanFlow = ai.defineFlow(
  {
    name: 'generateCustomMealPlanFlow',
    inputSchema: GenerateCustomMealPlanInputSchema,
    outputSchema: GenerateCustomMealPlanOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
